### ISSUE TITLE
todo example files + notebooks

### ISSUE THREAD

**Issue by sebastian-lapuschkin** [albermax/innvestigate#65]
- [x] investigate wonky mnist model behaviour: evaluate available optimizers.

- [x] extend mnist_lrp.py with all other methods.
- [x] clean up a bit. replace mnist_all_methods.py with content from mnist_lrp.py

- [x] clean up all_methods.py , merge with imagenet_lrp.py, rename imagenet_all_methods.py

- [x] coordinate content with example notebooks. drown notebooks in enlightening text
